#!/bin/bash

TEST=$1
shift

cd ~/wasm2sea/tests
wat2wasm ${TEST}.wat -o ${TEST}.wasm 2>/dev/null

cd ~/wasm2sea/build
./wasm2sea ../tests/${TEST}.wasm 2>/dev/null

cd ~/wasm2sea/third_party/dstogov-ir
if [[ "$TEST" == *nested_loop* ]]; then
    ./ir ../../build/${TEST}.ir -O0 --emit-c out.c 2>/dev/null
    sed -i '1s/^/int32_t local_0, local_1, local_2;\n/' out.c
elif [[ -f "../../build/${TEST}.ir" ]]; then
    num_funcs=$(grep -c '^{' ../../build/${TEST}.ir 2>/dev/null || echo 0)
    if [[ "$num_funcs" -le 1 ]]; then
        ./ir ../../build/${TEST}.ir --emit-c out.c 2>/dev/null
    fi
    # else: use out.c generated by wasm2sea via ir_emit_c
fi

if [[ "$TEST" == *store* ]] || [[ "$TEST" == *load* ]]; then
    if [[ "$TEST" == i64_* ]]; then
        cc -O2 -include stdint.h -include stdbool.h out.c run_varargs_ffi_mem_i64.c -o a.out \
           $(pkg-config --cflags --libs libffi) -lm -ldl -lpthread 2>/dev/null
    else
        cc -O2 -include stdint.h -include stdbool.h out.c run_varargs_ffi_mem.c -o a.out \
           $(pkg-config --cflags --libs libffi) -lm -ldl -lpthread 2>/dev/null
    fi
elif [[ "$TEST" == i64_* ]]; then
    cc -O2 -include stdint.h -include stdbool.h out.c run_varargs_ffi_i64.c -o a.out \
       $(pkg-config --cflags --libs libffi) -lm -ldl -lpthread 2>/dev/null
elif [[ "$TEST" == i32_wrap_* ]]; then
    cc -O2 -include stdint.h -include stdbool.h out.c run_varargs_ffi_i64_ret_i32.c -o a.out \
       $(pkg-config --cflags --libs libffi) -lm -ldl -lpthread 2>/dev/null
elif [[ "$TEST" == i32_trunc_* ]]; then
    cc -O2 -include stdint.h -include stdbool.h out.c run_varargs_ffi_f64_ret_i32.c -o a.out \
       $(pkg-config --cflags --libs libffi) -lm -ldl -lpthread 2>/dev/null
elif [[ "$TEST" == i64_trunc_* ]]; then
    cc -O2 -include stdint.h -include stdbool.h out.c run_varargs_ffi_f64_ret_i64.c -o a.out \
       $(pkg-config --cflags --libs libffi) -lm -ldl -lpthread 2>/dev/null
elif [[ "$TEST" == f64_convert_i32_* ]]; then
    cc -O2 -include stdint.h -include stdbool.h out.c run_varargs_ffi_f64.c -o a.out \
       $(pkg-config --cflags --libs libffi) -lm -ldl -lpthread 2>/dev/null
elif [[ "$TEST" == f64_convert_i64_* ]]; then
    cc -O2 -include stdint.h -include stdbool.h out.c run_varargs_ffi_i64_ret_f64.c -o a.out \
       $(pkg-config --cflags --libs libffi) -lm -ldl -lpthread 2>/dev/null
elif [[ "$TEST" == matmul* ]]; then
    cc -O2 -include stdint.h -include stdbool.h out.c run_varargs_ffi_matmul.c -o a.out \
       $(pkg-config --cflags --libs libffi) -lm -ldl -lpthread 2>/dev/null
elif [[ "$TEST" == bubble_sort* ]] || [[ "$TEST" == *sort* ]]; then
    cc -O2 -include stdint.h -include stdbool.h out.c run_varargs_ffi_sort.c -o a.out \
       $(pkg-config --cflags --libs libffi) -lm -ldl -lpthread 2>/dev/null
else
    cc -O2 -include stdint.h -include stdbool.h out.c run_varargs_ffi.c -o a.out \
       $(pkg-config --cflags --libs libffi) -lm -ldl -lpthread 2>/dev/null
fi

./a.out "$@"